//! Core types for patch operations

use serde::{Deserialize, Serialize};
use std::path::PathBuf;
use std::sync::Arc;

/// A patch operation type
#[derive(Debug, Clone, Copy, PartialEq, Eq, Deserialize, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum Operation {
    Replace,
    InsertBefore,
    InsertAfter,
    AppendEof,
    PrependBof,
    Overwrite,
}

/// Reindentation specification
#[derive(Debug, Clone, PartialEq, Eq, Deserialize, Serialize)]
pub struct Reindent {
    pub strip: Option<String>,
    pub add: Option<String>,
}

/// A single patch request
#[derive(Debug, Clone, PartialEq, Deserialize, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct PatchRequest {
    pub operation: Operation,
    pub old_text: Option<String>,
    pub new_text: Option<String>,
    /// Replace operation only: substitute every exact occurrence of `old_text`
    /// instead of requiring a unique match.
    // owned: predates the field; absent means single-match replace, which is the
    // correct default for every pre-feature request, so no migration is owed.
    #[serde(default)]
    pub replace_all: bool,
    pub to_clipboard: Option<String>,
    pub from_clipboard: Option<String>,
    pub reindent: Option<Reindent>,
}

/// Input for a patch operation
#[derive(Debug, Clone, PartialEq, Deserialize, Serialize)]
pub struct PatchInput {
    pub path: String,
    pub patches: Vec<PatchRequest>,
}

/// A located edit in the content
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EditSpec {
    pub offset: usize,
    pub length: usize,
}

/// An edit to apply
///
/// `replacement` is an `Arc<str>` so a single value can be shared cheaply across
/// many edits — a `replaceAll` over thousands of occurrences must not clone the
/// replacement text once per match.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Edit {
    pub offset: usize,
    pub length: usize,
    pub replacement: Arc<str>,
}

/// Effects produced by patch planning
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PatchEffect {
    /// Write content to a file (creates parent dirs as needed)
    WriteFile { path: PathBuf, content: String },
}

/// Result of planning patches
#[derive(Debug, Clone)]
pub struct PatchPlan {
    /// The effects to execute
    pub effects: Vec<PatchEffect>,
    /// The resulting content after patches
    #[allow(dead_code)] // Used in tests
    pub resulting_content: String,
    /// Generated diff for display
    pub diff: String,
    /// Warning if file appears auto-generated
    pub autogenerated_warning: bool,
}

/// A reported location for a non-unique `oldText` match.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DuplicateMatchLocation {
    pub start_line: usize,
    pub snippet: String,
}

/// Bounded diagnostics for a non-unique `oldText` match.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct DuplicateMatchDiagnostics {
    pub total: usize,
    pub reported: Vec<DuplicateMatchLocation>,
    pub omitted: usize,
}

impl std::fmt::Display for DuplicateMatchDiagnostics {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        writeln!(
            f,
            "oldText appears {} times in file (must be unique).",
            self.total
        )?;
        if !self.reported.is_empty() {
            writeln!(f, "Matching locations:")?;
            for location in &self.reported {
                writeln!(f, "- line {}:", location.start_line)?;
                for line in location.snippet.lines() {
                    writeln!(f, "  {line}")?;
                }
            }
            if self.omitted > 0 {
                writeln!(f, "... {} more matches omitted", self.omitted)?;
            }
        }
        write!(
            f,
            "All patches in one call resolve against the original file content simultaneously, \
             so each oldText must be unique on its own. Widen oldText with surrounding context \
             to disambiguate sites, or split into separate patch tool calls (each call sees the \
             file as updated by prior calls)."
        )
    }
}

/// Errors that can occur during patch planning
#[derive(Debug, Clone, PartialEq, Eq, thiserror::Error)]
pub enum PatchError {
    #[error("Cannot use anchor-based operations (replace, insert_before, insert_after) on non-existent file")]
    ReplaceOnNonexistent,

    #[error("Operation requires oldText")]
    MissingOldText,

    #[error("Clipboard '{0}' not found")]
    ClipboardNotFound(String),

    #[error("oldText not found in file")]
    OldTextNotFound,

    #[error("{0}")]
    OldTextNotUnique(DuplicateMatchDiagnostics),

    #[error("Edit extends beyond file content")]
    EditOutOfBounds,

    #[error("Two edits in this call target overlapping regions of the file; split them into separate patch calls")]
    OverlappingEdits,

    #[error("replaceAll is only valid with the replace operation")]
    ReplaceAllRequiresReplace,

    #[error(
        "replaceAll found no exact occurrence of oldText, but it nearly matches existing text \
         (differs by whitespace or Unicode lookalikes). replaceAll substitutes exact matches only \
         — copy the exact bytes from the file, or use a separate replace patch per site (those fuzzy-recover)."
    )]
    ReplaceAllInexact,

    #[error("Line does not start with expected prefix '{prefix}':\n{line}")]
    ReindentPrefixMismatch { prefix: String, line: String },

    #[error("No patches provided")]
    NoPatches,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_operation_deserialize() {
        let json = r#""replace""#;
        let op: Operation = serde_json::from_str(json).unwrap();
        assert_eq!(op, Operation::Replace);
    }

    #[test]
    fn test_patch_request_deserialize() {
        let json = r#"{
            "operation": "replace",
            "oldText": "hello",
            "newText": "world"
        }"#;
        let req: PatchRequest = serde_json::from_str(json).unwrap();
        assert_eq!(req.operation, Operation::Replace);
        assert_eq!(req.old_text, Some("hello".to_string()));
        assert_eq!(req.new_text, Some("world".to_string()));
    }
}
