export { FindBar, type FindBarProps } from './FindBar';
export { findLiteralMatches, type ViewerFindMatch, type ViewerFindResult } from './literalMatch';
export {
  createMatchId,
  createSurfaceKey,
  type FindSessionCommand,
  type FindSessionMatch,
  type FindSessionOpenState,
  type FindSessionState,
  type MatchId,
  type ReduceFindSessionResult,
  type SearchableSurface,
  type SearchableSurfaceKey,
  closeFindSession,
  createClosedFindSession,
  nextFindSessionMatch,
  openFindSession,
  previousFindSessionMatch,
  reduceFindSession,
  replaceFindSessionResults,
  resetFindSession,
  setFindSessionQueryAndResults,
  activateFindSessionMatch,
} from './findSession';
export {
  activeSessionMatchIndex,
  projectionMatchesToSessionMatches,
  type MatchIdentity,
} from './projectionSession';
export {
  buildBlockSearchProjection,
  buildConversationSearchProjection,
  buildDiffSearchProjection,
  buildFileSearchProjection,
  buildKeywordSearchOutputProjection,
  buildPatchOutputProjection,
  buildReadFileOutputProjection,
  type BlockSearchMatchTarget,
  type BlockSearchProjection,
  type BlockSearchSource,
  type ConversationFragmentRevealTarget,
  type ConversationSearchMatchTarget,
  type ConversationSearchProjection,
  type ConversationSearchSource,
  type ConversationTextFragmentRevealTarget,
  type DiffSearchMatchTarget,
  type DiffSearchProjection,
  type DiffSearchSource,
  type FileSearchMatchTarget,
  type FileSearchProjection,
  type FileSearchSource,
  type KeywordSearchFragment,
  type PatchFragment,
  type PatchOutputProjection,
  type PatchRevealTarget,
  type ReadFileFragment,
  type ReadFileOutputProjection,
  type ReadFileRevealTarget,
  type KeywordSearchOutputProjection,
  type SearchableSource,
  type SearchableSourceMatch,
  type SearchableSourceProjection,
} from './searchProjections';
export { useFindSession, type UseFindSessionOptions } from './useFindSession';
export {
  useViewerFind,
  type UseViewerFindOptions,
  type UseViewerFindReturn,
  type ViewerFindNavigateContext,
} from './useViewerFind';
export { useViewerFindKeyboardShortcut } from './useViewerFindKeyboardShortcut';
export {
  initialViewerFindState,
  viewerFindReducer,
  type ViewerFindAction,
  type ViewerFindState,
} from './viewerFindReducer';
